### ISSUE TITLE
Execute loop timing question

### ISSUE THREAD

**Issue by drmikecrowe** [AlexandreDecan/sismic#108]
My `asyncio` loop looks roughly like this:

```py
...
            while not self.closing:
                if self.trace: logger.debug("main_sm_task tick")
                await self._sm_loop()
                await asyncio.sleep(0.001)
...

    async def _sm_loop(self):
        try:
            for step in self.interpreter.execute():
                for attribute in [
                    "event",
                    "transitions",
                    "entered_states",
                    "exited_states",
                    "sent_events",
                ]:
                    if getattr(step, attribute):
                        logger.debug(f"{attribute}: {getattr(step, attribute)}")
        except Exception as ex:
            logger.error("StateMachine error", exc_info=ex)
```

My expectation is this will be running `interpreter.execute()` frequently.  However, I'm seeing a ~1.5s lag between queueing events and the state machine responding:

```
2021-03-10 07:09:46,903 [gui.systems.StateMachine] DEBUG: main_sm_task tick
2021-03-10 07:09:49,329 [gui.systems.StateMachine] DEBUG: main_sm_task tick
2021-03-10 07:09:51,822 [gui.systems.StateMachine] DEBUG: main_sm_task tick
2021-03-10 07:09:54,252 [gui.systems.StateMachine] DEBUG: main_sm_task tick
2021-03-10 07:09:56,685 [gui.systems.StateMachine] DEBUG: main_sm_task tick
2021-03-10 07:09:58,560 [gui.systems.StateMachine] DEBUG: main_sm_task tick
2021-03-10 07:10:00,996 [gui.systems.StateMachine] DEBUG: main_sm_task tick
```

IMO, this should be firing constantly, but I'm getting them every 1-2s.  Is there a param for loop timing I'm missing?

**Comment by AlexandreDecan** [comment]
Hello,

I've no idea, to be honest ;-) Did you try the `for step` loop outside of async and observe similar "lags"? If no, it's likely that the issue comes from something "async-related", but I've no idea (I've never used async in Python, unfortunately). 

Could you also try with `execute_once` instead of `execute`? Basically, the latter repetitively call the former until an "empty step" is returned (i.e. until there is no transition that is fired). If you have many transitions with no event (i.e. guard only transitions), this could affect the performances since all those guards have to be evaluated at least one more time to detect that none of them can be satisfied. If you get similar timings/lags with `execute_once` instead of `execute`, then I'm nearly 100% convinced that the problem comes from an "async-related" thing ;-)

**Comment by AlexandreDecan** [comment]
FWIW you could be interested in our implementation of an `AsyncRunner` (based on threads, not on `asyncio`): https://github.com/AlexandreDecan/sismic/blob/master/sismic/runner/runner.py

**Comment by AlexandreDecan** [comment]
Any news about this issue? ;-)

**Comment by drmikecrowe** [comment]
Yeah, it's a beast 😀

Behave now has async support, so that's positive.  However, it's setup to
run a task to completion and then terminate, which isn't necessarily what
I'm looking for (I don't think).

I'm still trying to work out how to load the state machine, run the execute
in an async task to collect the results and not close the loop

**Comment by AlexandreDecan** [comment]
Good luck :-D 

Did you find what was the reason for the "timing" issue you spotted?

**Comment by drmikecrowe** [comment]
Wow, sorry, forgot to update. Yes -- One of my pip packages had a 0.5s blocking function call I was frequently using (and didn't realize that call was blocking).  I moved that into a thread and that resolved the issue.  It was a call to get the current status of mplayer -- which is why I assumed a status call wouldn't have long delays built in

**Comment by AlexandreDecan** [comment]
I'm glad you found the issue, and also that it's not due to Sismic ;-)
