### ISSUE TITLE
Bind Interpreter issue

### ISSUE THREAD

**Issue by EdoardoBagnati** [AlexandreDecan/sismic#125]
Hi, I am trying to run three state charts simultaneously, and they communicate through internal events propagated externally. Unfortunately, the events are not always being captured correctly. I wanted to ask how to execute all the steps of these state charts concurrently multiple times. Attached are images of how I defined the queues and how I executed the state charts simultaneously. I am asking for help, please.
![Screenshot 2024-07-22 090526](https://github.com/user-attachments/assets/ef2c4872-9b08-4117-9666-8774f797d789)

**Comment by AlexandreDecan** [comment]
Hello,

Could you clarify what "events are not always captured correctly" means exactly? How did you bind the interpreters? Also, I think the `for loop` won't work correctly because of `zip` that stops when the shortest iterable is consumed (meaning that, if `execute1`, `execute2` and `execute3` differ in their length, the loop only consumes the shortest one, and won't iterate on the extra items present in the other iterables).

**Comment by EdoardoBagnati** [comment]
yes, i have 3 statecharts: machine, controller and buffer. I did not understand well if with the command bind.interpreter can run three state charts at the same time even if with different lengths of queues and that exchange events between them, as in the attachment where in the state chart of the controller I wrote "send (M7_start_op)" and in the statechart machine "M7_start_op" to capture the external event of the other and continue the flow in the statechart. 
![Screenshot 2024-07-22 224448](https://github.com/user-attachments/assets/64587db4-b4db-406d-b22e-99e00baff60f)
![Screenshot 2024-07-22 224502](https://github.com/user-attachments/assets/4d96d9c8-9a05-4843-9f08-5c336d7cad7d)
![Screenshot 2024-07-22 224548](https://github.com/user-attachments/assets/30492d1b-475a-4f78-b5ea-8c740c88290e)
![Screenshot 2024-07-22 224559](https://github.com/user-attachments/assets/462c5885-a6f4-49e0-a9a4-838ca7032fd2)
In the attachment, I leave a part of the writing in yamal and the output that I have in the terminal, in the previous question there is the execute of the three statecharts. Thanks for the clarification about whether I can run three statecharts at once or I have to shape them so that their queues are sequential and not contemporary.

**Comment by AlexandreDecan** [comment]
But what is the problem/question exactly?

**Comment by EdoardoBagnati** [comment]
The question is, can I run all three statecharts simultaneously and link them with bind.interpreter (communicating via events)? Or should they be performed the event queues sequentially and not simultaneously?

Inviato da Outlook per iOS<https://aka.ms/o0ukef>
________________________________
Da: Alexandre Decan ***@***.***>
Inviato: Tuesday, July 23, 2024 9:03:22 AM
A: AlexandreDecan/sismic ***@***.***>
Cc: Edoardo Bagnati ***@***.***>; Author ***@***.***>
Oggetto: Re: [AlexandreDecan/sismic] Bind Interpreter issue (Issue #125)


But what is the problem/question exactly?

**Comment by AlexandreDecan** [comment]
"Simultaneously" is misleading since it means using threads or processes. However, there's nothing preventing the use of multiple statecharts "at the same time". See the documentation for running concurrent statecharts: https://sismic.readthedocs.io/en/latest/concurrent.html  I believe this is what you are looking for.

**Comment by AlexandreDecan** [comment]
I'm closing this issue for now but feel free to reopen it if needed.
