### ISSUE TITLE
story generator based on mutation

### ISSUE THREAD

**Issue by aliparsai** [AlexandreDecan/sismic#35]
Story generator based on mutation testing is now working. However, the mutation operators are very simple for now, so the stories that are being generated are not that good. I will focus my efforts on developing all Fabbri mutation operators.

There's a slight issue in the way of completely automating the process:

We still need an item list to be submitted to the story generator. So far I used "events_for()" method to get all possible events. but this is not always working, because events usually need additional parameters (for example floor, in case of floorSelecting event). I'm still unclear how we can make this part automatic as well without some form of python parser. Maybe it is a good idea to introduce a DSL instead of python code, so that this part can be automated as well.

**Comment by AlexandreDecan** [comment]
I understand the problem you are facing with. Tom already asked for a DSL to specify the set of "possible events", including event parameters, but I don't like the idea because this is not "the way to do" in Python. And I know my answer does not solve your problem;)

Maybe you can allow the user to manually specify parametrized events and to override some events from ``events_for()``. For example, one could do:

```python
events = my_statechart.events_for()
floorSelected = events.pop(Event('floorSelected')
floorSelected = parametrize_event(floorSelect, {'floor': int})
events.append(floorSelected)
```

The ``parametrize_event`` function should take an Event and return an Event with some additional parameters that are useful for you to mutate the event.

**Comment by AlexandreDecan** [comment]
Another way to circumvent the problem is to manually provide the list of events that should be considered for the automatic story generation. For example, ``[Event('floorSelected', floor=4), Event('dummyEvent')]``. 

This way, you can access the ``data`` attribute of an ``Event`` instance to see which are the parameters that are defined. Based on their types (here ``int``), you can even do some mutations on the value.

**Comment by aliparsai** [comment]
Currently, it is getting an item list as an input, so we can include whatever we want manually. But, if we can somehow know if an event needs a parameter, and the type and the range of that parameter, we can already ignore the rest of the embedded python code, and probably generate meaningful events. For this to work, we might need a minimal python parser, or we can just let the user to provide this info in addition to the python code (If this is too similar to what Tom said, then just ignore it!).

**Comment by aliparsai** [comment]
"""This way, you can access the data attribute of an Event instance to see which are the parameters that are defined. Based on their types (here int), you can even do some mutations on the value."""

^^ This might work. I'm gonna try it

**Comment by AlexandreDecan** [comment]
Another solution is to execute the story and see if it raises an ``AttributeError`` (you can even patch on-the-fly an ``Event`` if needed) and deduce the name of each expected parameter (ok, we still lack information about its type)

**Comment by AlexandreDecan** [comment]
FYI, I implemented a built-in support for Behavior-driven development into Sismic.
It relies on Behave, a well-known Python library for BDD.

Please have a look at the [docs](http://sismic.readthedocs.org/en/stable/behavior.html)!
I believe that something interesting can be done with BDD and mutation testing.
