### ISSUE TITLE
Join pseudostate

### ISSUE THREAD

**Issue by sbidoul** [AlexandreDecan/sismic#75]
HI,

First of all, congratulations and many thanks for this excellent library.

I was wondering how to implement a [join pseudostate](https://www.uml-diagrams.org/state-machine-diagrams.html#join-pseudostate)? I did not find native support for it in Sismic, and I could not imagine a clean way to emulate it so far (perhaps there is one?).

Fork pseudo states are less of an issue as in most use cases we always use the same initial entry point in parallel states.

**Comment by tommens** [comment]
Fork/Join pseudostates are currently not implemented in SISMIC because until now we never found a need for them (even if they are part of the UML standard); they are more suited for activity diagrams instead of statecharts. For all examples we could think of, we were always able to find a clean way of modeling the statechart without the need for such pseudostates. Do you happen to have a motivating example of a statechart for which a join pseudostate would be useful? On the basis of such an example we could discuss and reflect on whether it would be useful and feasible to provide support for it.

**Comment by AlexandreDecan** [comment]
I'm writing from my smartphone so don't mind the conciseness of my answer :-) you can use a single transition outgoing from the parallel state with a guard relying on "active(...)" to simulate a basic join pseudo state.

**Comment by sbidoul** [comment]
@AlexandreDecan thanks! I'll try that.

**Comment by sbidoul** [comment]
So easy. Works like a charm, thanks again!
