### ISSUE TITLE
Provide a simple Python example, with GUI, using a sismic interpreter as backend

### ISSUE THREAD

**Issue by tommens** [AlexandreDecan/sismic#9]
To illustrate the use of sismic, I would suggest to add (in the docs, or as a tutorial) something similar in spirit to what can be found here for SCXML:
https://commons.apache.org/proper/commons-scxml/usecases/scxml-stopwatch.html

The idea is to show a very simple example of a GUI in Python (with some button that trigger events), where the "backend" is basically simply a statechart that is being interpreted dynamically each time one of the buttons is pressed. (It does not have to be the stopwatch example, it can be any other example, as long as it is simple and illustrative.)

Such an example will illustrate to potential users how seismic can be integrated directly in user code, if desired. (Of course, in this example we should also add, as usual, the necessary contracts, and we could also write the necessary tests for it.)

**Comment by AlexandreDecan** [comment]
I think this can indeed be interesting to add. Can you make some suggestions for the example(s) I'll implement? I find the Stopwatch example a bit uninteresting as most of the behavior is already self-contained in Java code...

**Comment by tommens** [comment]
Everything depends on how simple or large the example needs to be. The Stopwatch example had the advantage of being simple, but you consider it to be too simple.

A more complex example would be the Cruise Control of a car. (Let's start with a simple version of it.) Essentially, to control the cruise control there are 4 buttons or so, and there is a non-trivial behaviour behind the events triggered by the use of these buttons. I have already modelled this example with Yakindu, so the statechart for the example is already available (but not yet in YAML I believe).

Other exemples (but probably more difficult to create a simple GUI for it would be : the microwave example; and automatic drink or food dispenser;  the elevator example). I would go for the cruise control.

**Comment by tommens** [comment]
After giving it a night of sleep, a hot drink dispenser could be a nice example: the GUI could be relatively simple (with a few buttons for selecting/choosing the type of drink and amount of sugar, buttons or a text field for simulating the insertion of coins, a visual display showing the status) and the statechart behind it would contain state like Off, Active and OutOfOrder. Active could have substates Waiting (the machine is waiting for a customer), SelectingDrink (the user inserts coins, chooses a drink and the amount of sugar), Processing (the machine is preparing and returning the drink and exchange coins). OutOfOrder will be when there are no drinks left, not enough coins left, no sugar left, no cups left, and so on. The machine could return to the normal states by refilling the stock of drinks, coins, sugar and/of cups. Here is a version of the statechart but it could be adapted
[DrinkDistributor.pdf](https://github.com/AlexandreDecan/sismic/files/81122/DrinkDistributor.pdf)

And what about the example of a Chronometer and Stopwatch functionality? (I already completely modelled this one with Yakindu and in Java). It is similar to the stopwatch, but not quite. Here is an example statechart for it, but it could be replaced by using two parallel states for Timer and Stopwatch, so that both can run in parallel (which is currently not the case)
[TimerStopwatch.pdf](https://github.com/AlexandreDecan/sismic/files/81124/TimerStopwatch.pdf)

**Comment by AlexandreDecan** [comment]
Before integrating the example in the documentation, could you please give me some feedback?
This is the revisited Stopwatch example. Unless the example in the commons-scxml documentation, I managed to put the whole logic of the timer in the statechart, without an intermediate (and useless) class (like *StopWatch.java*). 

Here is the YAML definition:
https://github.com/AlexandreDecan/sismic/blob/master/examples/stopwatch.yaml

The statechart encodes three components: 
 - A timer component, that has a start/stop behavior and increments the timer. 
 - A split/unsplit component that represents the current "split" state. 
 - A display component, that refresh the value to be displayed

This statechart can be easily executed with a tiny GUI, as shown in the following Python script:
https://github.com/AlexandreDecan/sismic/blob/master/examples/stopwatch.py

As you can see, most of the code is related to tkinter (which is a "tiny" UI library). Lines 21 to 30 shows how to create an interpreter for the Stopwatch, and how to bind events. The example relies on ``run_in_background`` function for convenience. Ideally, one should use tkinter's mainloop to update interpreter's internal time and to call ``execute``. 

Notice that this example will NOT work with the current PyPi version of Sismic (0.12.2). The code expects the ``bind`` function of an interpreter to accept any callable, which is something that is only available starting from 0.12.3. Similarly, the code already makes use of the newly exposed ``context`` of an interpreter, and the newly created ``stop`` method of the ``Thread`` instance returned by ``run_in_background``. 

In order to run the example, you should clone the *master* branch of this repository (or wait until I put the latest version on PyPi).

**Comment by AlexandreDecan** [comment]
Sorry, I didn't see your message before posting mine. As you will see, my stopwatch is more like yours than commons-scxml's one.

**Comment by tommens** [comment]
I will have a look at your example, hopefully today (if I do not have time you can show me tomorrow...)

**Comment by AlexandreDecan** [comment]
I made a small update of the example to eliminate the use of ``run_in_background`` and to use Tkinter's mainloop instead. This allowed me to explain where *non-event-driven" widget updates should occur.

**Comment by AlexandreDecan** [comment]
We'll discuss about this tomorrow. 
I already put the example in the documentation. 
https://sismic.readthedocs.org/en/latest/advancedtopics/integrate_code.html
