### ISSUE TITLE
Allow the use of initial transition

### ISSUE THREAD

**Issue by leonwilly** [AlexandreDecan/sismic#93]
In the SCXML specification the initial property can be a state or a transition.  This allows for an action that might initialize specific contexts that a state might need.  Could you add this feature or would you like me to look into adding it?  

```yaml
initial:
  - target: ready
    action: warmup()
```

**Comment by gabewillen** [comment]
I am aware this can be circumvented by using eventless transitions.  Its just more verbose adding a intermediate state that the state machine never settles on and only passes through.

**Comment by AlexandreDecan** [comment]
Hello,

This behavior can be simulated without going through an intermediate state (which indeed is more verbose and not very clean) and eventless transitions, using the "on entry" property of the parent composite state: 

```yaml
- name: parent
  initial: ready
  on entry: warmup()
```

**Comment by AlexandreDecan** [comment]
Btw, this is not going to solve all cases. Feel free to submit a PR (even an empty one at first so we can discuss on how to properly support these initial transitions, as such a change is likely to have many implications on the existing code base).

Thanks

**Comment by AlexandreDecan** [comment]
Any news on this issue?

**Comment by gabewillen** [comment]
Sorry kids got sick and my wife is pregnant so I haven't gotten around to looking into this.  I will submit a pull request and we can start discussing implementation.

**Comment by AlexandreDecan** [comment]
No worries. I expect this change will have many implications in Sismic and will not be easy to implement. I won't have a lot of time to spend on it unfortunately (and I imagine you won't either, with a baby on the way). It remains to be seen whether the benefits of a "true initial transition" are worth the effort.

**Comment by gabewillen** [comment]
An update I am back on this now that the baby is here and things have settled. I anticipate a pull request in the next few weeks. I will maintain the same coding standards and style you have throughout.

**Comment by AlexandreDecan** [comment]
Congrats for the baby! I wish you the best ;) (and some spare time, whenever possible ;-))

**Comment by gabewillen** [comment]
Okay so I couldn't create an empty pull request. Apparently Github won't allow pull requests when the repositories are identical. I have this implemented but now I am confused.

the SCXML specification states 

> 
> **3.1.4 Initial, Final, and History States**
> ...
> (If neither the <initial> child or the 'initial' element is specified, the default initial state is the first child state in document order.)
> ...

I have implemented both features however in your elevator example I have a test failing its PlantUML output.
here is the yaml snippet from the elevator (line 29) that is against SCXML spec and your documentation.

```
          - name: moving
            transitions:
              - target: doorsOpen
                guard: destination == current
                action: doors_open = True
            states:
              - name: movingUp
                on entry: current = current + 1
                transitions:
                  - target: movingUp
                    guard: destination > current
              - name: movingDown
                on entry: current = current - 1
                transitions:
                  - target: movingDown
                    guard: destination < current
```
moving is a composite state and therefor must have a initial property / initial transition or a default one in this case _movingUp_ will be assigned. 

Are you going away from the SCXML spec in this regard? UML specification does allow for composite states without initial transitions. If this is in fact intentional I'll change the added first child element initial requirement.  Please advise on this and I'll wrap up the rest of testing and submit a pull request. I actually like the UML specification in this aspect. Always having a initial state becomes verbose. 

Thanks

**Comment by gabewillen** [comment]
This would comply with the SCXML spec.

```
          - name: movement
            transitions:
              - target: doorsOpen
                guard: destination == current
                action: doors_open = True
            states:
              - name: idle
              - name: movingUp
                on entry: current = current + 1
                transitions:
                  - target: movingUp
                    guard: destination > current
              - name: movingDown
                on entry: current = current - 1
                transitions:
                  - target: movingDown
                    guard: destination < current
```

Of course the rest of the example would need to be changes also.

**Comment by gabewillen** [comment]
Looking at this further I see that moving is just a transient state and is never actually settled on. So implementation wise having an initial is just a technicality and it wouldn't actually be used by the interpreter. So I think I can solve this on my own as its just a matter of declaration. The initial is implied but doesn't have to be on the chart.

**Comment by AlexandreDecan** [comment]
I'm not sure I fully understood your last message :-) 

Anyway, you're right: we don't conform 100% with scxml, especially when UML is precise enough only to define, without ambiguity, the expected behavior. Sismic allows the creation of composite states without imposing the definition of an initial state. This makes sense, indeed, in the case of transient states. 

Contrary to SCXML, we always had the will not to depend on the order of the elements in the document to define the semantics of statechart execution. This is the reason why it is possible not to have an initial state, rather than taking the first available state in the document order. It is also the reason why other aspects of execution may differ from SCXML, as indicated in the documentation (for example, multiple transitions triggered simultaneously, or in the presence of parallel states, see the first subsection of https://sismic.readthedocs.io/en/latest/execution.html for more information).

**Comment by gabewillen** [comment]
Sorry I was kind of thinking out loud in a sense. I understand your reasoning and I also prefer the UML specification in this regard. I see plenty of use cases where it makes sense that the compound state doesn't have an initial transition. I just wasn't sure if you wanted to stick to a specification or if you were kind of mixing and matching.

**Comment by AlexandreDecan** [comment]
Personally, I do not really care about the specification, as long as it is non-ambiguous and "obvious to the user". But I know that @tommens does not fully agree with this point of view, and prefer to stay as close as possible to UML :)

Historically, I started developing Sismic because we wanted to do research on statechart testing, and I hadn't found any statechart simulator whose semantics was not (too) ambiguous. So, I started writing Sismic by trying (in this order) to stick to UML as much as possible, then to SCXML for the cases where UML was ambiguous, then to common sense for the cases where SCXML failed on this :-)

**Comment by tommens** [comment]
Yes, I think we should stay as close to the "standard UML" statechart semantics whenever possible, and only deviate from it when UML is ambiguous or when we have another convincing reason for it. One of the reasons is that I want to use Sismic for UML teaching purposes so the closer to UML the better.

**Comment by tommens** [comment]
Another reason is that staying closer to UML would make it easier to "import" statecharts from other UML compliant tools (we do not have specific goals to do this at a short term), and to facilitate the use of Sismic by users that are already acquainted with the UML notation and semantics (which is more widespread than the SCXML one).

**Comment by gabewillen** [comment]
I agree 100% with tommens. I just thought this project was leaning more towards SCXML standard. I am actually in the process of writing a compile time state machine framework in C++17 for work. I think the UML specification is robust and predictable.  I struggle to write code now without using state machines. Although I primarily write real-time software for industrial machinery. I can’t stand spaghetti code with if / else if / else statements spread throughout.

**Comment by devanshanker** [comment]
In the end were any features ever added to support any modefiers for the `initial` transition of a state? Just looking to display actions on initial transitions for a research project I am working on using sismic for statechart visualizations + translation into modeling/synthesis tools.

**Comment by AlexandreDecan** [comment]
As far as I remember we made no specific change related to this issue, since the desired behaviour can be obtained quite easily with the current set of features.

**Comment by devanshanker** [comment]
Was not able to achieve the desired behavior based on the information above – would you mind providing a brief example of a labeled edge on an (init) transition within the current set of features? Was not able to figure out how to do this without adjusting the PlantUML file directly. Much appreciated!

**Comment by AlexandreDecan** [comment]
Since "initial transitions" are implicit in Sismic, the key is to create an additional state, with an automatic transition. For example:

```yaml
 - name: composite
   initial: initial_state
   states:
    - name: initial_state
      transitions: 
       - target: kind_of_second_initial_state
         action: your_python_code()
    - name: kind_of_second_initial_state  
```
